[package]
name = "rusty-mcrouter-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bytes.workspace = true
rusty-mcrouter-config = { path = "../rusty-mcrouter-config" }
rusty-mcrouter-net = { path = "../rusty-mcrouter-net" }
rusty-mcrouter-protocol = { path = "../rusty-mcrouter-protocol" }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
bytes.workspace = true
rusty-mcrouter-net = { path = "../rusty-mcrouter-net", features = ["testing"] }
tokio = { workspace = true, features = ["full"] }
