[package]
name = "rusty-mcrouter-observability"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
testing = []

[dependencies]
rusty-mcrouter-net = { path = "../rusty-mcrouter-net" }
tokio = { workspace = true, features = ["net", "io-util", "rt", "sync", "macros", "time"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
