[package]
name = "rusty-mcrouter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bytes.workspace = true
clap = { version = "4", features = ["derive", "env"] }
rusty-mcrouter-config = { path = "../rusty-mcrouter-config" }
rusty-mcrouter-core = { path = "../rusty-mcrouter-core" }
rusty-mcrouter-net = { path = "../rusty-mcrouter-net" }
rusty-mcrouter-protocol = { path = "../rusty-mcrouter-protocol" }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }

[dev-dependencies]
testcontainers = "0.21"
tokio = { workspace = true, features = ["full"] }
