[package]
name = "rusty-mcrouter-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
testing = []

[dependencies]
bytes.workspace = true
rusty-mcrouter-protocol = { path = "../rusty-mcrouter-protocol" }
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "io-util"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
