[package]
name = "rusty-mcrouter-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
testing = ["rusty-mcrouter-protocol/testing"]

[dependencies]
bytes.workspace = true
rusty-mcrouter-observability-primitives = { path = "../rusty-mcrouter-observability-primitives" }
rusty-mcrouter-protocol = { path = "../rusty-mcrouter-protocol" }
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "rt", "sync", "macros", "time"] }

[dev-dependencies]
rusty-mcrouter-observability-primitives = { path = "../rusty-mcrouter-observability-primitives", features = ["testing"] }
rusty-mcrouter-protocol = { path = "../rusty-mcrouter-protocol", features = ["testing"] }
tokio = { workspace = true, features = ["full", "test-util"] }
